# Generated by Django 5.2.5 on 2025-09-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterUser',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
